-- A slightly altered version of catppucchin mocha
local colorscheme = {
  background = '#1e1e2e',
  compose_cursor = '#f2cdcd',
  cursor_bg = '#f5e0dc',
  cursor_border = '#f5e0dc',
  cursor_fg = '#11111b',
  foreground = '#cdd6f4',
  scrollbar_thumb = '#585b70',
  selection_bg = '#585b70',
  selection_fg = '#cdd6f4',
  split = '#6c7086',
  visual_bell = '#313244',

  ansi = {
    '#45475a',
    '#ff5555',
    '#4d9375',
    '#f9e2af',
    '#89b4fa',
    '#f5c2e7',
    '#94e2d5',
    '#bac2de',
  },
  brights = {
    '#585b70',
    '#f38ba8',
    '#a6e3a1',
    '#f9e2af',
    '#89b4fa',
    '#f5c2e7',
    '#94e2d5',
    '#a6adc8',
  },
  tab_bar = {
    background = '#11111b',
    inactive_tab_edge = '#313244',
    active_tab = {
      bg_color = '#cba6f7',
      fg_color = '#11111b',
      intensity = 'Normal',
      italic = false,
      strikethrough = false,
      underline = 'None',
    },
    inactive_tab = {
      bg_color = '#181825',
      fg_color = '#cdd6f4',
      intensity = 'Normal',
      italic = false,
      strikethrough = false,
      underline = 'None',
    },
    inactive_tab_hover = {
      bg_color = '#1e1e2e',
      fg_color = '#cdd6f4',
      intensity = 'Normal',
      italic = false,
      strikethrough = false,
      underline = 'None'
    },
    new_tab = {
      bg_color = '#313244',
      fg_color = '#cdd6f4',
      intensity = 'Normal',
      italic = false,
      strikethrough = false,
      underline = 'None',
    },
    new_tab_hover = {
      bg_color = '#45475a',
      fg_color = '#cdd6f4',
      intensity = 'Normal',
      italic = false,
      strikethrough = false,
      underline = 'None',
    },
  },
  indexed = {
    [16] = '#fab387',
    [17] = '#f5e0dc',
  },
}

return colorscheme
